package com.hdcardenas2.model;
// Generated May 24, 2018 8:34:39 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * DetailUsersRoll generated by hbm2java
 */
@Entity
@Table(name="detail_users_roll"
    ,catalog="test"
)
public class DetailUsersRoll  implements java.io.Serializable {


     private Integer id;
     private Roll roll;
     private Users users;

    public DetailUsersRoll() {
    }

    public DetailUsersRoll(Roll roll, Users users) {
       this.roll = roll;
       this.users = users;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="roll_id", nullable=false)
    public Roll getRoll() {
        return this.roll;
    }
    
    public void setRoll(Roll roll) {
        this.roll = roll;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="user_id", nullable=false)
    public Users getUsers() {
        return this.users;
    }
    
    public void setUsers(Users users) {
        this.users = users;
    }




}


