package com.hdcardenas2.model;
// Generated May 24, 2018 8:34:39 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Roll generated by hbm2java
 */
@Entity
@Table(name="roll"
    ,catalog="test"
)
public class Roll  implements java.io.Serializable {


     private Integer id;
     private String name;
     private Set detailUsersRolls = new HashSet(0);

    public Roll() {
    }

	
    public Roll(String name) {
        this.name = name;
    }
    public Roll(String name, Set detailUsersRolls) {
       this.name = name;
       this.detailUsersRolls = detailUsersRolls;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    
    @Column(name="name", nullable=false, length=65535)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="roll")
    public Set getDetailUsersRolls() {
        return this.detailUsersRolls;
    }
    
    public void setDetailUsersRolls(Set detailUsersRolls) {
        this.detailUsersRolls = detailUsersRolls;
    }

    @Override
    public String toString() {
        return "Roll{" + "id=" + id + ", name=" + name + '}';
    }




}


