package com.hdcardenas2.model;
// Generated May 24, 2018 8:34:39 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Users generated by hbm2java
 */
@Entity
@Table(name="users"
    ,catalog="test"
)
public class Users  implements java.io.Serializable {


     private Integer id;
     private String user;
     private String password;
     private Set detailUsersRolls = new HashSet(0);

    public Users() {
    }

	
    public Users(String user, String password) {
        this.user = user;
        this.password = password;
    }
    public Users(String user, String password, Set detailUsersRolls) {
       this.user = user;
       this.password = password;
       this.detailUsersRolls = detailUsersRolls;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    
    @Column(name="user", nullable=false, length=65535)
    public String getUser() {
        return this.user;
    }
    
    public void setUser(String user) {
        this.user = user;
    }

    
    @Column(name="password", nullable=false, length=65535)
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="users")
    public Set getDetailUsersRolls() {
        return this.detailUsersRolls;
    }
    
    public void setDetailUsersRolls(Set detailUsersRolls) {
        this.detailUsersRolls = detailUsersRolls;
    }




}


